export const AnimeActionTypes = {

    ANIME_LOADING: "ANIME_LOADING",
    ANIME_LOADED_SUCCESS: "ANIME_LOADED_SUCCESS",
    ANIME_INFORMATION_LOADED_SUCCESS: "ANIME_INFORMATION_LOADED_SUCCESS",
    GO_TO_ANIME: "GO_TO_ANIME"
    
};